package com.nenrys.mutroleum.item;

import com.nenrys.mutroleum.Mutroleum;
import com.nenrys.mutroleum.misc.ModCreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ModItems {

    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, Mutroleum.MOD_ID);

    public static final RegistryObject<Item> P_MUTROLEUM = ITEMS.register("p_mutroleum",
            () -> new Item(new Item.Properties().tab(ModCreativeModeTab.MUTROLEUM_TAB)));

    public static final RegistryObject<Item> SPECIES_ITEM = ITEMS.register("species_item",
            () -> new SpeciesItem(new Item.Properties().tab(ModCreativeModeTab.MUTROLEUM_TAB)));

    public static final RegistryObject<Item> MUTROLIC_FRUIT = ITEMS.register("mutrolic_fruit",
            () -> new MutrolicFoodItem(new Item.Properties().tab(ModCreativeModeTab.MUTROLEUM_TAB).food(ModFoods.FRUIT_NON_CARRIER), ModFoods.FRUIT_CARRIER));

    //autogenerated items, do not change __0__
	public static final RegistryObject<Item> C_MUTROLEUM = ITEMS.register("c_mutroleum", 
		() -> new Item(new Item.Properties().tab(ModCreativeModeTab.MUTROLEUM_TAB)));

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }

}
