package com.nenrys.mutroleum.item;

import com.nenrys.mutroleum.Mutroleum;
import com.nenrys.mutroleum.misc.ModCreativeModeTab;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ModItems {

    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, Mutroleum.MOD_ID);

    public static final RegistryObject<Item> P_MUTROLEUM = ITEMS.register("p_mutroleum",
            () -> new Item(new Item.Properties().tab(ModCreativeModeTab.MUTROLEUM_TAB)));

    //autogenerated items, do not change __0__
	public static final RegistryObject<Item> C_MUTROLEUM = ITEMS.register("c_mutroleum", 
		() -> new Item(new Item.Properties().tab(ModCreativeModeTab.MUTROLEUM_TAB)));

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }

}
